name: FPL
channels:
  - defaults
dependencies:
  - pip=21.2.2
  - python=3.9.6
  - sqlite=3.36.0
  - pip:
    - apache-airflow==2.1.2
    - numpy==1.21.1
    - pandas==1.3.1
    - scikit-learn==0.24.2
    - requests==2.26.0